BlogSite/Controllers/AuthorizationController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net.Http;
using System.Net.Mail;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.WebPages;
using BLL.IServices;
using BLL.Validator;
using BlogSite.Cyrpto;
using DAL.DataContext;
using DTO.UserDto;
using Entities;
using FluentValidation;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using ValidationException = FluentValidation.ValidationException;

namespace BlogSite.Controllers
{
    public class AuthorizationController : Controller
    {
        private readonly IUserService _userService;
        public AuthorizationController(IUserService userService)
        {
            _userService = userService;
        }
        #region REGiSTER
        //REGISTER
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Registration(string returnUrl)
        {
            bool b = await _userService.CheckIfUserExist(User.Identity.Name);
            var Countries = await _userService.Countries();
            List<Country> countries = await _userService.Countries();
            ViewBag.Countries = new SelectList(countries, "CountryId", "CountryName");
            if (b)
            {
                return RedirectToAction("Index", "Blog");
            }
            else
            {
                ViewBag.ReturnUrl = returnUrl ?? Url.Action("Index", "Blog");
                return View();
            }
         ;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registration(RegistrationDto model)
        {
            bool Status = false;
            string message = "";
            List<Country> countries = await _userService.Countries();
            ViewBag.Countries = new SelectList(countries, "CountryId", "CountryName");
            if (ModelState.IsValid)
            {
                if (await VerifyEmail(model.Authentication.Email))
                {
                    #region if email is in database
                    var isExist = await EmailExsist(model.Authentication.Email);
                    if (isExist)
                    {
                        ModelState.AddModelError("EmailExist", "Email already Exist");
                        ViewBag.ErorrMessage = "Email already Exist";
                        return View(model);
                    }
                    else
                    {
                        #region password hashing
                        model.Authentication.Password = Cyrpto1.Hash(model.Authentication.Password);
                        model.Authentication.ConfirmPassword = Cyrpto1.Hash(model.Authentication.ConfirmPassword);
                        #endregion

                        #region Check User's Age
                        var currentDate = DateTime.Now;
                        var UserBirth = model.Birth;
                        if (currentDate.Month >= UserBirth.Month)
                        {
                            model.Age = currentDate.Year - UserBirth.Year;
                        }
                        else
                        {
                            model.Age = currentDate.Year - UserBirth.Year - 1;
                        }

                        #endregion

                        try
                        {
							await _userService.Create(model);
							return RedirectToAction("Index", "Blog");
						}
						catch(ValidationException ex)
                        {
							foreach (var error in ex.Errors)
							{
								ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
							}

							return View(model);
						}

                    }
                }
                else
                {
                    ModelState.AddModelError("Email Valid", "Email is not valid");
                    ViewBag.ErorrMessage = "Email is not valid";
                    return View(model);
                }

                #endregion
            }
            else
            {
                message = "Invalid Request";
            }
            return View(model);
        }
        //[NonAction]
        //public async Task<bool> isEmailExsist(string Email)
        //{
        //    var users = await _userService.GetUsers();
        //    var v = users.Where(x => x.Email.ToLower() == Email.ToLower()).FirstOrDefault();
        //    return v != null;
        //}


        [NonAction]
        [HttpPost]
        //Check if email is valid to register 
        public async Task<bool> VerifyEmail(string email)
        {
            var apiKey = "d024e18eb35fbd7dc2505dd4966612c252ccbaf3";
            var client = new HttpClient();
            var response = await client.GetAsync($"https://api.hunter.io/v2/email-verifier?email={email.ToLower()}&api_key={apiKey}");
            var json = await response.Content.ReadAsStringAsync();
            var data = JsonConvert.DeserializeObject<dynamic>(json);
            var result = data.data.result;
            return result == "deliverable";
        }

        [NonAction]
        public async Task<bool> EmailExsist(string Email)
        {
            var emails = await _userService.Emails();
            if (emails.Contains(Email.ToLower()))
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        //REGISTER
        #endregion REGISTER
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Login(string returnUrl)
        {
            string email = User.Identity.Name;
            if (await _userService.CheckIfUserExist(email.ToLower()))
            {
                return RedirectToAction("Index", "Blog");
            }
            ViewBag.ReturnUrl = returnUrl ?? Url.Action("Index", "Blog");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(UserLoginDto user)
        {

            var userauthentications = await _userService.Get();
            var users3 = userauthentications.Where(x => x.Email.ToLower() == user.Authentication.Email.ToLower()).FirstOrDefault();
            
            if (users3 != null)
            {
				var id = await _userService.IdOfLoggedUser(users3.Email);
				var result = users3.Password.CompareTo(Cyrpto1.Hash(user.Authentication.Password));
                if (result == 0)
                {
                    //string authenticationScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    //// Generate Claims from DbEntity
                    //var claims = new List<Claim>
                    //{
                    //new Claim(ClaimTypes.Name,user.Authentication.Email),
                    //new Claim(ClaimTypes.Email,user.Authentication.Email),

                    //};

                    //ClaimsIdentity claimsIdentity = new ClaimsIdentity(
                    //        claims, authenticationScheme);

                    //ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(
                    //        claimsIdentity);

                    //var authProperties = new AuthenticationProperties
                    //{
                    //    // AllowRefresh = <bool>,
                    //    // Refreshing the authentication session should be allowed.
                    //    // ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),
                    //    // The time at which the authentication ticket expires. A 
                    //    // value set here overrides the ExpireTimeSpan option of 
                    //    // CookieAuthenticationOptions set with AddCookie.
                    //    IsPersistent = true,
                    //    // Whether the authentication session is persisted across 
                    //    // multiple requests. Required when setting the 
                    //    // ExpireTimeSpan option of CookieAuthenticationOptions 
                    //    // set with AddCookie. Also required when setting 
                    //    // ExpiresUtc.
                    //    // IssuedUtc = <DateTimeOffset>,
                    //    // The time at which the authentication ticket was issued.
                    //    //RedirectUri = "~/Blog/Index"
                    //    // The full path or absolute URI to be used as an http 
                    //    // redirect response value.
                    //};
                    var claims = new List<Claim>
                     {
                     new Claim(ClaimTypes.Name, user.Authentication.Email),
                     new Claim(ClaimTypes.NameIdentifier,id.ToString()),
                     };
                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                    return RedirectToAction("Index", "Blog");
                }
                else
                {
                    ModelState.AddModelError("", "Password is Incorrect");
                    return View();
                }
            }
            else
            {
                ModelState.AddModelError("", "Email is not exist");
                return View();
            }

        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Blog");
        }
    }
}

BlogSite/Views/Authorization/Login.cshtml
@using DTO.UserDto
@model UserLoginDto
@{
	ViewData["Title"] = "View";
	Layout = "~/Views/Shared/UserLayout.cshtml";
}


<section class="main-content-w3layouts-agileits">
	<div class="container">
		<h3 class="tittle">Sign In Now</h3>
		<div class="row inner-sec">
			<div class="login p-5 bg-light mx-auto mw-100">
				<form asp-action="Login" asp-controller="Authorization">
					<div class="text-danger" asp-validation-summary="All"></div>
					<div class="form-group">
						<label asp-for="Authentication.Email" class="mb-2">Email address</label>
						<input type="email" class="form-control" asp-for="Authentication.Email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" required="">
						<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
					</div>
					<div class="form-group">
						<label asp-for="Authentication.Password" class="mb-2">Password</label>
						<input type="password" class="form-control" asp-for="Authentication.Password" id="exampleInputPassword1" placeholder="" required="">
					</div>
					<div class="form-check mb-2">
						<input type="checkbox" class="form-check-input" id="exampleCheck1">
						<label class="form-check-label" for="exampleCheck1">Check me out</label>
					</div>
					<input type="submit" class="btn btn-primary submit mb-4">
					<p><a href="/Authorization/Registration"> Don't have an account?</a></p>
				</form>
			</div>
		</div>
	</div>
</section>

BlogSite/Views/Authorization/Registration.cshtml
@using DTO.UserDto
@model RegistrationDto
@{
	Layout = "/Views/Shared/UserLayout.cshtml";
}


<section class="main-content-w3layouts-agileits">
	<div class="container">
		<h3 class="tittle">Register Now</h3>
		@if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
		{
			if (ViewBag.Message != null)
			{
				<div class="alert alert-success">
					<strong>Success!</strong>@ViewBag.Message
				</div>
			}
		}
		else
		{
			<div class="inner-sec">
				<div class="login p-5 bg-light mx-auto mw-100">
					<div class="text-danger validationcls" asp-validation-summary="All"></div>
					<form asp-controller="Authorization" asp-action="Registration" method="post">
						@if (ViewBag.Message != null)
						{
							<div class="alert alert-danger">
								<strong>Error!</strong>@ViewBag.Message
							</div>
						}

						<div class="form-row">
							<div class="col-md-4 mb-3">
								<label for="validationCustom01">First name</label>
								<input type="text" asp-for="FirstName" class="form-control" id="validationDefault01" placeholder="" required="">
							</div>
							<div class="col-md-4 mb-3">
								<label for="validationCustom02">Last name</label>
								<input type="text" asp-for="LastName" class="form-control" id="validationDefault02" placeholder="" required="">
							</div>
							<div class="col-md-4 mb-3">
								<label for="validationCustom02">Birth </label>
								<input type="date" onchange="formatDate()" id="date" asp-for="Birth" pattern="DD/MM/YYYY"  placeholder="dd-mm-yyyy" class="form-control"   required="">
							</div>

						</div>
						<div class="form-row">
							<div class="form-group col-md-4">
								<label asp-for="Authentication.Email" class="mb-2">Email</label>
								<input type="email" asp-for="Authentication.Email" class="form-control" placeholder="" required="">
							</div>
							<div class="form-group col-md-4">
								<label asp-for="Authentication.Password" class="mb-2">Password</label>
								<input type="password" asp-for="Authentication.Password" class="form-control" id="password1" placeholder="" required="">
							</div>
							<div class="form-group col-md-4">
								<label asp-for="Authentication.ConfirmPassword" class="mb-2">Confirm Password</label>
								<input type="password" asp-for="Authentication.ConfirmPassword" class="form-control" id="password2" placeholder="" required="">
							</div>
						</div>
						<div class="form-row ">
							<div class="form-group col-md-5">
								<label style="margin:0 auto" class="mb-2">Select Country</label>
								<select class="form-control forborder" asp-for="CountryId" asp-items="@(@ViewBag.Countries)"></select>
							</div>
							<div class="form-group col-md-5">
								<input style="margin-left:80px;margin-top: 32px !important;" type="submit" value="Register" id="idh1" class="btn btn-primary  mb-2">
							</div>
						</div>
					</form>
				</div>
			</div>
		}
	</div>
</section>



<style>
	.validationcls {
		margin-top: -1vw;
		margin-bottom: 3vw;
		margin-left: 28vw
	}
</style>

<script>
	  function formatDate() {
    var date = new Date(document.getElementById("date").value);
    var options = { day: '2-digit', month: '2-digit', year: 'numeric'};
    document.getElementById("date").value = date.toLocaleDateString("en-GB", options);
</script>